In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np


In [9]:
## array creation 
arr1 = np.array([1,2,3,4,5,6])
#print(arr1)
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
arr2 = np.arange(1,6)
arr2

array([1, 2, 3, 4, 5])

In [3]:
arr4 = np.ones(5)
arr4

NameError: name 'np' is not defined

In [6]:
arr5 = np.linspace(1,10,5)  # 1 - 10 --> range and 5 is no. of elements . mtlb 1 to 10 ka bech m ketna no.cheya
arr5

NameError: name 'np' is not defined

In [ ]:
## 2d array

In [8]:
arr6 = np.arange(60).reshape(6,10) ## reshap total no. ka multiple 6 rows 10 coloumns
arr6   

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [9]:
arr6.shape ## rows and columns
arr6.dtype
arr6.size
arr6.ndim

2

In [10]:
## random numbers sa error create krne h tb
arr8 = np.random.random(10) ## hr baar alg alg np. melnga o/p m
arr8

array([0.31812505, 0.28509443, 0.62818991, 0.58064224, 0.16228361,
       0.63506253, 0.06413094, 0.96597544, 0.13776347, 0.81860825])

In [11]:
arr9 = np.random.randint(1,10,100) ## random no. int m
arr9

array([8, 9, 1, 5, 2, 8, 9, 9, 7, 8, 3, 6, 4, 6, 1, 7, 9, 7, 3, 4, 9, 3,
       6, 6, 2, 6, 4, 2, 8, 9, 1, 3, 9, 9, 3, 4, 2, 9, 3, 6, 5, 2, 9, 6,
       1, 6, 2, 1, 6, 4, 1, 3, 5, 8, 1, 1, 8, 7, 3, 9, 2, 4, 4, 4, 7, 9,
       4, 2, 7, 6, 4, 7, 3, 7, 4, 4, 8, 5, 2, 8, 1, 6, 4, 7, 4, 3, 8, 9,
       5, 7, 3, 2, 5, 6, 2, 6, 8, 9, 9, 6], dtype=int32)

In [12]:
print(arr6.shape) ## rows and columns
arr6.dtype
arr6.size
arr6.ndim

arr6.T.shape  ## transpose

(6, 10)


(10, 6)

In [13]:
## higher dimension array ko 1 dimension array m convert kr dta h 
arr6.flatten() 
arr6.ravel()
## both performing same work

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [14]:
##3d array
arr9 = np.random.randint(1,10,(3,4))
arr9

array([[4, 9, 6, 6],
       [9, 7, 4, 5],
       [2, 3, 8, 1]], dtype=int32)

In [15]:
arr9 = np.arange(225).reshape(3,15,5)  ## 15,5 --> rows and 3--> table
arr9

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [16]:
np.max(arr9)
np.min(arr9)
np.mean(arr9)
np.median(arr9)
np.std(arr9)

np.float64(64.95126378036586)

In [17]:
arr7 = np.ones((2,3))
arr7

array([[1., 1., 1.],
       [1., 1., 1.]])